[wip] 第8回 スコア
k-hamada/HAL pull request #23
Opened 2017-06-27 12:47 UTC by kanais7

## 概要

2017-06-28 03:30 UTC, kanais7 commented
:memo::zatsu:
![scale](https://user-images.githubusercontent.com/8970098/27619460-69c0ce74-5bfd-11e7-8ba0-ebd3e3751d61.gif)

2017-07-04 06:10 UTC, k-hamada requested changes

2017-07-04 06:10 UTC, k-hamada commented on Client/Assets/Scripts/MainController.cs
> +    Vector3 CulcPlayerScale(int score)
`s/Culc/Calc/`

2017-07-04 06:14 UTC, kanais7 commented on Client/Assets/Scripts/MainController.cs
> +    Vector3 CulcPlayerScale(int score)
:dogeza:

2017-07-04 06:17 UTC, k-hamada approved these changes

2017-07-04 06:17 UTC, k-hamada commented
![](http://i.imgur.com/W2B3qNd.gif)

2017-07-04 06:17 UTC, merged